import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingOverlay from "@/components/loading/loading-circle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { LoadingOverlayStoreProvider } from "@/providers/loading-overlay-provider";
import LoadingOverlayUI from "@/components/global-ui/loading-overlay-ui";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingOverlayStoreProvider initialData={{ name: '' }}>
          {children}
          <LoadingOverlayUI />
        </LoadingOverlayStoreProvider>
      </body>
    </html>
  );
}
